"""voice preferences

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 10:11:14.713332+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tts_voice", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("tts_speed", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "tts_speed")
    op.drop_column("users", "tts_voice")
    # ### end Alembic commands ###
