"""resolution labels

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 06:35:02.515906+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resolution_labels",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("existing_memory_id", sa.String(length=64), nullable=False),
        sa.Column("existing_content", sa.Text(), nullable=False),
        sa.Column("existing_category", sa.String(length=32), nullable=False),
        sa.Column("existing_subject", sa.String(length=200), nullable=True),
        sa.Column("existing_confidence", sa.Float(), nullable=False),
        sa.Column("existing_age_days", sa.Float(), nullable=False),
        sa.Column("incoming_memory_id", sa.String(length=64), nullable=False),
        sa.Column("incoming_content", sa.Text(), nullable=False),
        sa.Column("incoming_category", sa.String(length=32), nullable=False),
        sa.Column("incoming_subject", sa.String(length=200), nullable=True),
        sa.Column("judge_relation", sa.String(length=16), nullable=True),
        sa.Column("judge_confidence", sa.Float(), nullable=True),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("gate", sa.Float(), nullable=True),
        sa.Column("forced", sa.Boolean(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("expected_action", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_resolution_labels_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_labels")),
    )
    op.create_index(
        "ix_resolution_labels_user_created",
        "resolution_labels",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_resolution_labels_user_created", table_name="resolution_labels")
    op.drop_table("resolution_labels")
    # ### end Alembic commands ###
