"""learning and memory improvements

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 10:38:14.432935+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_feedback",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("used_ids", sa.JSON(), nullable=False),
        sa.Column("cited_ids", sa.JSON(), nullable=False),
        sa.Column("missing_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_answer_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_feedback")),
    )
    op.create_index(
        "ix_answer_feedback_user_created",
        "answer_feedback",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "extraction_feedback",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("memory_id", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("source_excerpt", sa.Text(), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_extraction_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_feedback")),
    )
    op.create_index(
        "ix_extraction_feedback_user_created",
        "extraction_feedback",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "resolution_rules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_resolution_rules_created_by_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resolution_rules")),
    )
    op.create_index(op.f("ix_resolution_rules_owner"), "resolution_rules", ["owner"], unique=False)
    op.add_column(
        "resolution_labels", sa.Column("graph_owner", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resolution_labels", "graph_owner")
    op.drop_index(op.f("ix_resolution_rules_owner"), table_name="resolution_rules")
    op.drop_table("resolution_rules")
    op.drop_index("ix_extraction_feedback_user_created", table_name="extraction_feedback")
    op.drop_table("extraction_feedback")
    op.drop_index("ix_answer_feedback_user_created", table_name="answer_feedback")
    op.drop_table("answer_feedback")
    # ### end Alembic commands ###
